# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stop Bullying Tour
email: info@stopbullyingtour.org
description: >- # this means to ignore newlines until "baseurl:"
  Taking the Solution to bullying on the Road
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stopbullyingtour.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stopbullyingtour
github_username:  
timezone: America/New_York
# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-time-to-read
  - jekyll-paginate-v2
  - jekyll-algolia


exclude: [Gemfile,Gemfile.lock, README.md, node_modules, vendor/bundle/,vendor/cache/, vendor/gems/, vendor/ruby/]


#{% for post in site.categories.trips limit:3 %}

#Paginate Settings
pagination: 
  enabled: true
  debug: true
  per_page: 5
  permalink: ':num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  sort_reverse: true

# SASS Settings
sass:
  sass_dir: _sass
  style: compressed


# Permalink Configuration
permalink: /blog/:year/:month/:title/
category_dir: "blog"
category_layout: "index.html"
# Directory used by the data_to_pages plugin.
tag_dir: 'blog/category'

# Collections
collections:
  bod:
    output: true
    permalink: /about-us/board-of-directors/:slug/
  team:
    output: true
    permalink: /about-us/our-team/:slug/
  blog:
    output: true
    permalink: /blog/:slug/


algolia:
  application_id: 'F0ZXEIRMX4'
  index_name:     'StopBullyingTour'
    